//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCERCISE_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXCERCISE_CATEGORY()
        {
            this.EXERCISEs = new HashSet<EXERCISE>();
        }
    
        public int EXCERCISE_CATEGORY_ID { get; set; }
        public string EXCERCISE_CATEGORY_NAME { get; set; }
        public string EXCERCISE_CATEGORY_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXERCISE> EXERCISEs { get; set; }
    }
}
