//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_TAKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_TAKE()
        {
            this.STOCK_TAKE_LINE = new HashSet<STOCK_TAKE_LINE>();
        }
    
        public int STOCK_TAKE_ID { get; set; }
        public System.DateTime STOCK_TAKE_DATE { get; set; }
        public string STOCK_TAKE_NOTES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_TAKE_LINE> STOCK_TAKE_LINE { get; set; }
    }
}
