//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD_HISTORY
    {
        public int PASSWORD_ID { get; set; }
        public System.DateTime PASSWORD_DATE { get; set; }
        public string HASHED_PASSWORD { get; set; }
        public int USERS_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
