//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_PRICE_HISTORY
    {
        public int BOOKING_PRICE_HISTORY_ID { get; set; }
        public System.DateTime BOOKING_PRICE_HISTORY_DATE { get; set; }
        public decimal BOOKING_PRICE_HISTORY_AMOUNT { get; set; }
        public int BOOKING_TYPE_ID { get; set; }
    
        public virtual BOOKING_TYPE BOOKING_TYPE { get; set; }
    }
}
