//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_ATTENDANCE
    {
        public int BOOKING_ID { get; set; }
        public int SCHEDULE_ID { get; set; }
        public bool ATTENDED { get; set; }
        public int RECEIPT_ID { get; set; }
    
        public virtual BOOKING BOOKING { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
        public virtual SCHEDULE SCHEDULE { get; set; }
    }
}
