//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.LESSONs = new HashSet<LESSON>();
        }
    
        public int USERS_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_SURNAME { get; set; }
        public byte[] EMPLOYEE_PHOTO { get; set; }
        public string EMPLOYEE_SA_ID { get; set; }
        public int QUALIFICATION_ID { get; set; }
        public int EMPLOYEE_CONTRACT_ID { get; set; }
        public int EMPLOYEE_TYPE_ID { get; set; }
    
        public virtual EMPLOYEE_CONTRACT EMPLOYEE_CONTRACT { get; set; }
        public virtual EMPLOYEE_TYPE EMPLOYEE_TYPE { get; set; }
        public virtual QUALIFICATION QUALIFICATION { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LESSON> LESSONs { get; set; }
    }
}
