//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCISE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXERCISE()
        {
            this.LESSON_PLAN = new HashSet<LESSON_PLAN>();
        }
    
        public int EXCERCISE_ID { get; set; }
        public string EXCERCISE_NAME { get; set; }
        public string EXCERCISE_DESCRIPTION { get; set; }
        public int EXCERCISE_CATEGORY_ID { get; set; }
    
        public virtual EXCERCISE_CATEGORY EXCERCISE_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LESSON_PLAN> LESSON_PLAN { get; set; }
    }
}
