//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY_ITEM()
        {
            this.STOCK_TAKE_LINE = new HashSet<STOCK_TAKE_LINE>();
            this.SUPPLIER_ORDER_LINE = new HashSet<SUPPLIER_ORDER_LINE>();
            this.WRITE_OFF_LINE = new HashSet<WRITE_OFF_LINE>();
        }
    
        public int INVENTORY_ITEM_ID { get; set; }
        public int SALE_ITEM_ID { get; set; }
        public decimal INVENTORY_ITEM_COST_PRICE { get; set; }
        public int INVENTORY_ITEM_QUANTITY { get; set; }
    
        public virtual SALE_ITEM SALE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_TAKE_LINE> STOCK_TAKE_LINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_ORDER_LINE> SUPPLIER_ORDER_LINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WRITE_OFF_LINE> WRITE_OFF_LINE { get; set; }
    }
}
