//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_HISTORY
    {
        public int PRICE_HISTORY_ID { get; set; }
        public int SALE_ITEM_ID { get; set; }
        public System.DateTime PRICE_DATE { get; set; }
        public decimal PRICE_AMOUNT { get; set; }
    
        public virtual SALE_ITEM SALE_ITEM { get; set; }
    }
}
