//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEIPT()
        {
            this.BOOKING_ATTENDANCE = new HashSet<BOOKING_ATTENDANCE>();
            this.REFUNDs = new HashSet<REFUND>();
            this.SALE_LINE = new HashSet<SALE_LINE>();
        }
    
        public int RECEIPT_ID { get; set; }
        public System.DateTime RECEIPT_DATE_TIME { get; set; }
        public double RECEIPT_TOTAL_VAT { get; set; }
        public double RECEIPT_TOTAL_AMOUNT { get; set; }
        public int PAYMENT_TYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING_ATTENDANCE> BOOKING_ATTENDANCE { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFUND> REFUNDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_LINE> SALE_LINE { get; set; }
    }
}
