//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_LINE
    {
        public int SALE_LINE_ID { get; set; }
        public int SALE_LINE_QUANTITY { get; set; }
        public int CLIENT_ID { get; set; }
        public int SALE_ID { get; set; }
        public int SALE_ITEM_ID { get; set; }
        public int RECEIPT_ID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
        public virtual SALE SALE { get; set; }
        public virtual SALE_ITEM SALE_ITEM { get; set; }
    }
}
