//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE_ITEM()
        {
            this.INVENTORY_ITEM = new HashSet<INVENTORY_ITEM>();
            this.PRICE_HISTORY = new HashSet<PRICE_HISTORY>();
            this.SALE_LINE = new HashSet<SALE_LINE>();
            this.STOCK_TAKE_LINE = new HashSet<STOCK_TAKE_LINE>();
        }
    
        public int SALE_ITEM_ID { get; set; }
        public string SALE_ITEM_NAME { get; set; }
        public byte[] SALE_ITEM_PHOTO { get; set; }
        public string SALE_ITEM_DESCRIPTION { get; set; }
        public decimal SALE_ITEM_PRICE { get; set; }
        public bool SALE_ITEM_QUOTABLE { get; set; }
        public int SALE_ITEM_QUANTITY { get; set; }
        public int SALE_CATEGORY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_ITEM> INVENTORY_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRICE_HISTORY> PRICE_HISTORY { get; set; }
        public virtual SALE_CATEGORY SALE_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_LINE> SALE_LINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_TAKE_LINE> STOCK_TAKE_LINE { get; set; }
    }
}
