//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCHEDULE()
        {
            this.BOOKING_ATTENDANCE = new HashSet<BOOKING_ATTENDANCE>();
        }
    
        public int SCHEDULE_ID { get; set; }
        public int SCHEDULE_CAPACITY_BOOKED { get; set; }
        public int VENUE_ID { get; set; }
        public int BOOKING_TYPE_ID { get; set; }
        public int LESSON_PLAN_ID { get; set; }
        public int DATE_SESSION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING_ATTENDANCE> BOOKING_ATTENDANCE { get; set; }
        public virtual BOOKING_TYPE BOOKING_TYPE { get; set; }
        public virtual DATE_SESSION DATE_SESSION { get; set; }
        public virtual LESSON_PLAN LESSON_PLAN { get; set; }
        public virtual VENUE VENUE { get; set; }
    }
}
