//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_TAKE_LINE
    {
        public int STOCK_TAKE_ID { get; set; }
        public int INVENTORY_ITEM_ID { get; set; }
        public int SALE_ITEM_ID { get; set; }
        public int STOCK_TAKE_LINE_DIFFERENCE { get; set; }
    
        public virtual INVENTORY_ITEM INVENTORY_ITEM { get; set; }
        public virtual SALE_ITEM SALE_ITEM { get; set; }
        public virtual STOCK_TAKE STOCK_TAKE { get; set; }
    }
}
