//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER_ORDER()
        {
            this.SUPPLIER_ORDER_LINE = new HashSet<SUPPLIER_ORDER_LINE>();
        }
    
        public int SUPPLIER_ORDER_ID { get; set; }
        public System.DateTime SUPPLIER_ORDER_DATE { get; set; }
        public int ORDER_STATUS_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
    
        public virtual ORDER_STATUS ORDER_STATUS { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_ORDER_LINE> SUPPLIER_ORDER_LINE { get; set; }
    }
}
