//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CLIENTs = new HashSet<CLIENT>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.PASSWORD_HISTORY = new HashSet<PASSWORD_HISTORY>();
        }
    
        public int USERS_ID { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_CELL { get; set; }
        public int USER_ROLE_ID { get; set; }
        public int TITLE_ID { get; set; }
        public int NOTIFICATION_TYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASSWORD_HISTORY> PASSWORD_HISTORY { get; set; }
        public virtual TITLE TITLE { get; set; }
        public virtual USER_ROLE USER_ROLE { get; set; }
    }
}
