//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT
    {
        public int VAT_ID { get; set; }
        public decimal VAT_PRICE { get; set; }
        public System.DateTime VAT_DATE { get; set; }
    }
}
