//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRITE_OFF_LINE
    {
        public int INVENTORY_ITEM_ID { get; set; }
        public int WRITE_OFF_ID { get; set; }
        public int WRITE_OFF_LINE_QUANTITY { get; set; }
        public int WRITE_OFF_REASON_ID { get; set; }
    
        public virtual INVENTORY_ITEM INVENTORY_ITEM { get; set; }
        public virtual WRITE_OFF WRITE_OFF { get; set; }
        public virtual WRITE_OFF_REASON WRITE_OFF_REASON { get; set; }
    }
}
