//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRITE_OFF_REASON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WRITE_OFF_REASON()
        {
            this.WRITE_OFF_LINE = new HashSet<WRITE_OFF_LINE>();
        }
    
        public int WRITE_OFF_REASON_ID { get; set; }
        public string WRITE_OFF_REASON_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WRITE_OFF_LINE> WRITE_OFF_LINE { get; set; }
    }
}
